name: "French Pressicus-Technicalus"
subtitle: "the common cafe nerd"
signature: "Eric Drechsel, Investigative Nerd"
taginfo:
  main:
    icon: "home"
    url: "/"
  things:
    icon: "gift"
    url: "/things"
  done:
    icon: "gift"
    url: "/things"
pygments: true
permalink: "pretty"
markdown: "redcarpet"
relative_permalinks: false
github:
  repo: "edrex/edrex.github.io"
  branch: "master"
prose:
  siteurl: "http://edrex.github.io"
  relativeLinks: "http://edrex.github.io/links.json"
  media: "media"