name: "French Press"
description: "diary of a common cafe nerd"
signature: "Eric Drechsel, Investigative Nerd"
siteurl: "http://eric.pdxhub.org"
taginfo:
  main:
    icon: "home"
    url: "/"
  things:
    icon: "gift"
    url: "/things"
  done:
    icon: "gift"
    url: "/things"
pygments: true
permalink: "pretty"
markdown: "redcarpet"
relative_permalinks: false
github:
  repo: "edrex/edrex.github.io"
  branch: "master"
prose:
  siteurl: "http://eric.pdxhub.org"
  relativeLinks: "http://eric.pdxhub.org/links.json"
  media: "media"