name: "Doohicky"
description: "a site about nothing"
signature: "Yours truly, Grizzly Bear"
pygments: true
permalink: pretty
markdown: redcarpet
github:
  # enables "edit" link
  repo: 'edrex/edrex.github.io'
  branch: master
prose:
  siteurl: 'http://GRIZZLYBEAR.github.io'
  relativeLinks: 'http://GRIZZLYBEAR.github.io/links.jsonp'
  media: 'media'
