name: "Publish GH Pages"
on:
  # Run only when pushing to main branch
  push:
    branches:
      - main
jobs:
  emanote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build emanote site 🔧
        run: |
          # rm README.md
          mkdir -p output.docker 
          docker run --tmpfs /tmp -v $PWD:/data sridca/emanote emanote --layers /data gen /data/output.docker
          cp -r output.docker output  # Ditch docker created root-owned files
      - name: Deploy to gh-pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output/
          cname: eric.pdxhub.org
